### PR TITLE
update to latest version

### PR DESCRIPTION
**Pull request by chrisbutler**

### CODE REVIEW

**Comment by chrisbutler** [comment]
hey @zol, i noticed that there's a slightly new version of the snippet and the npm package is up to 2.0.0. it would be awesome to get this updated on atmosphere

**Comment by zol** [comment]
Hey @chrisbutler - thanks for your PR! I'd be happy to accept it as long as you change the package version to be `2.0.0_1` . The `_1` indicates that this is the first 'wrapped' release of the upstream version.

**Comment by chrisbutler** [comment]
@zol got it, done

**Comment by zol** [comment]
Merged and release, thanks @chrisbutler - hope it works :)

**Pull request merged**
